server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
spring:
  application:
    name: GateWay

zuul:
  prefix: /api
  routes:
    product-service: /item/**
    upload-service:
      path: /upload/**
      service-id: upload-service
      strip-prefix: false

ribbon:
  ReadTimeout: 60000 #ribbon超时时长
  ConnectTimeout: 60000 # ribbon读取超时时长
  MaxAutoRetries: 0  # 当前服务重试次数
  MaxAutoRetriesNextServer: 0 # 切换服务重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 990000 # 熔断超时时长：6000ms